version: '2'
services:
  #mesin1 -- copykan untuk mesin 2,3, dst
  mesin1:
    container_name: ds-mesin-1
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    ports:
      - 8888:8888
    networks:
      ds-network:
        ipv4_address: 172.16.17.101
  mesin2:
    container_name: ds-mesin-2
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    ports:
      - 8889:8888
    networks:
      ds-network:
        ipv4_address: 172.16.17.102
  mesin3:
    container_name: ds-mesin-3
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    ports:
      - 9000:8888
    networks:
      ds-network:
        ipv4_address: 172.16.17.103
  mesin4:
    container_name: ds-mesin-4
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    ports:
      - 9001:8888
    networks:
      ds-network:
        ipv4_address: 172.16.17.104
  mesin5:
    container_name: ds-mesin-5
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    ports:
      - 9002:8888
    networks:
      ds-network:
        ipv4_address: 172.16.17.105

networks:
  ds-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.17.0/24
          gateway: 172.16.17.1
